
[world]

	[world.biomes]

		[world.biomes.rainforest]
			"Rainforest weight" = 0.5
			"Rainforest Mountains weight" = 0.5
			"Rainforest Plateau weight" = 0.05
			"Sparse Rainforest Plateau weight" = 0.05
			"Rainforest Basin weight" = 0.5
			"Sparse Rainforest Basin weight" = 0.05

		[world.biomes.dunes]
			"Dunes weight" = 2.5
			"Dunes Hills weight" = 0.25
			"Flourishing Dunes weight" = 0.25
			"Rocky Dunes weight" = 2
			"Rocky Dunes Hills weight" = 0.2
			"Petrified Dunes weight" = 0.2

		#These biomes are experimental and not ready for use in gameplay
		[world.biomes.experimental]

			[world.biomes.experimental.hot_springs]
				"Hot Springs weight" = 0

